# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
    ]
